// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLYoR5Ttg6ALazm_a_vwKDbvgDAt6JFLg',
    appId: '1:374546642159:web:c4c6f40807cf06f4fcd71a',
    messagingSenderId: '374546642159',
    projectId: 'ristorante-c94d2',
    authDomain: 'ristorante-c94d2.firebaseapp.com',
    storageBucket: 'ristorante-c94d2.appspot.com',
    measurementId: 'G-6WG4K5XC8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1D2SoP_5KU-gPAQdNTr-jNX4aFcFWDnk',
    appId: '1:374546642159:android:2e2813d56d59eef4fcd71a',
    messagingSenderId: '374546642159',
    projectId: 'ristorante-c94d2',
    storageBucket: 'ristorante-c94d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdd9V6TRMR68dRh4xLBdVtAHRyoAC0MA4',
    appId: '1:374546642159:ios:32d891f8511eb8e9fcd71a',
    messagingSenderId: '374546642159',
    projectId: 'ristorante-c94d2',
    storageBucket: 'ristorante-c94d2.appspot.com',
    iosBundleId: 'com.example.ordiniRistorante',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdd9V6TRMR68dRh4xLBdVtAHRyoAC0MA4',
    appId: '1:374546642159:ios:2ea45173bc59f587fcd71a',
    messagingSenderId: '374546642159',
    projectId: 'ristorante-c94d2',
    storageBucket: 'ristorante-c94d2.appspot.com',
    iosBundleId: 'com.example.ordiniRistorante.RunnerTests',
  );
}
